Revert "Don't let vignette write to global env by default"
This reverts commit 25879242afe1180284c014804120a649095e2172.

For some reason, this fails on Windows when `R CMD check` attempts
to rebuild the user guide. I confirmed I get the same result locally.
This isn't critical enough to justify the troubleshooting required.

https://github.com/abbvie-external/OmicNavigator/runs/4227295993?check_suite_focus=true#step:16:131

  --- finished re-building 'OmicNavigatorAPI.Rnw'

  --- re-building 'OmicNavigatorUsersGuide.Rnw' using Sweave
  Error: processing vignette 'OmicNavigatorUsersGuide.Rnw' failed with
diagnostics:
  at OmicNavigatorUsersGuide.Rnw:267, object 'basal.vs.lp' not found
  --- failed re-building 'OmicNavigatorUsersGuide.Rnw'

  SUMMARY: processing the following file failed:
    'OmicNavigatorUsersGuide.Rnw'